# Generated by Django 4.2.6 on 2024-03-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('employee', 'employee')], default='customer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='Default address', max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('designation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login_registration.designation')),
                ('profile', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login_registration.profile')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('address', models.CharField(default='Default address', max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('profile', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login_registration.profile')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
