# Generated by Django 4.2.6 on 2024-03-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
