# Generated by Django 4.2.6 on 2024-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_remove_servicebooking_email_and_more'),
        ('login_registration', '0002_customer_company_address_customer_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='package',
            field=models.ManyToManyField(through='display.employee_package_schedule', to='display.packagebooking'),
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(through='display.employee_service_schedule', to='display.servicebooking'),
        ),
    ]
