# Generated by Django 5.0.1 on 2024-01-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login_registration', '0002_remove_customuser_cpassword_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='customer',
        ),
    ]
