# Generated by Django 4.2.6 on 2024-02-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
