# Generated by Django 4.2.6 on 2024-02-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_remove_customer_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
