# Generated by Django 5.0.1 on 2024-01-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_remove_customuser_is_staff_account_and_more'),
        ('login_registration', '0004_rename_customer_customuser'),
    ]

    operations = [
    ]
