# Generated by Django 4.2.6 on 2024-02-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
