# Generated by Django 4.2.6 on 2024-03-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0006_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=50)),
                ('employee', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login_registration.employee')),
            ],
            options={
                'db_table': 'designation',
            },
        ),
    ]
