# Generated by Django 4.2.6 on 2024-03-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0007_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='employee',
        ),
    ]
