# Generated by Django 4.2.6 on 2024-03-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0008_remove_designation_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designation',
            table='Designation',
        ),
    ]
