# Generated by Django 5.0.1 on 2024-01-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
