# Generated by Django 4.2.6 on 2024-03-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0009_alter_designation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='designation',
        ),
        migrations.AddField(
            model_name='designation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
