# Generated by Django 4.2.6 on 2024-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0010_remove_designation_designation_designation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
