# Generated by Django 5.0.1 on 2024-01-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0010_alter_customer_table_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
