# Generated by Django 5.0.1 on 2024-01-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0011_remove_employee_name_employee_address_employee_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
