# Generated by Django 4.2.6 on 2024-03-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0012_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
