# Generated by Django 5.0.1 on 2024-01-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0012_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default='Default address', max_length=255, null=True),
        ),
    ]
