# Generated by Django 5.0.1 on 2024-01-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0013_alter_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='Default address', max_length=255, null=True),
        ),
    ]
