# Generated by Django 4.2.6 on 2024-03-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0013_remove_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login_registration.designation'),
        ),
    ]
