# Generated by Django 5.0.1 on 2024-01-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0014_alter_employee_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
