# Generated by Django 4.2.6 on 2024-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_alter_customer_address_and_more'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_customers',
            field=models.ManyToManyField(related_name='enrolled_courses', to='login_registration.customer'),
        ),
    ]
