# Generated by Django 4.2.6 on 2024-02-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Course',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
