# Generated by Django 4.2.6 on 2024-02-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_tag_course_delete_prerequisite_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='Course',
            new_name='course',
        ),
    ]
