# Generated by Django 4.2.6 on 2024-03-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0006_delete_email'),
        ('course', '0005_remove_course_active_remove_course_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
            ],
            options={
                'db_table': 'course_booking',
            },
        ),
    ]
