# Generated by Django 5.0.1 on 2024-02-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
