# Generated by Django 4.2.6 on 2024-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_booking',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
