# Generated by Django 4.2.6 on 2024-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_booking',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
