# Generated by Django 4.2.6 on 2024-03-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_booking_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_booking',
            name='datetime',
        ),
    ]
