# Generated by Django 5.0.1 on 2024-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_email_alter_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
