# Generated by Django 4.2.6 on 2024-03-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0006_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(default=None, max_length=1000, null=True, upload_to='services/')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='serviceBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.services')),
            ],
            options={
                'db_table': 'service_booking',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.services')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.packages')),
            ],
            options={
                'db_table': 'package_booking',
            },
        ),
        migrations.CreateModel(
            name='employee_service_schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration.employee')),
                ('servbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.servicebooking')),
            ],
            options={
                'db_table': 'employee_service_schedule',
            },
        ),
    ]
