# Generated by Django 4.2.6 on 2024-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(default=None, max_length=1000, null=True, upload_to='services/')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
