# Generated by Django 4.2.6 on 2024-02-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
            ],
            options={
                'db_table': 'service_booking',
            },
        ),
    ]
