# Generated by Django 5.0.1 on 2024-01-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='Services',
        ),
    ]
