# Generated by Django 4.2.6 on 2024-03-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_service_schedule',
            old_name='id',
            new_name='service_schedule_id',
        ),
    ]
