# Generated by Django 4.2.6 on 2024-03-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0006_delete_email'),
        ('display', '0002_rename_id_employee_service_schedule_service_schedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_package_schedule',
            fields=[
                ('package_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration.employee')),
                ('packbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.packagebooking')),
            ],
            options={
                'db_table': 'employee_package_schedule',
            },
        ),
    ]
