# Generated by Django 4.2.6 on 2024-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_remove_servicebooking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='no_of_accounts',
            field=models.IntegerField(default=None),
        ),
    ]
