# Generated by Django 5.0.1 on 2024-01-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='services/'),
        ),
    ]
