# Generated by Django 4.2.6 on 2024-04-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_packagebooking_no_of_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='duration',
        ),
    ]
