# Generated by Django 4.2.6 on 2024-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_employee_package_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
