# Generated by Django 4.2.6 on 2024-02-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_rename_message_service_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='phone',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
