# Generated by Django 5.0.1 on 2024-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
