# Generated by Django 4.2.6 on 2024-02-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_service_booking_service_alter_service_booking_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_booking',
            old_name='service',
            new_name='service_id',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='phone',
        ),
    ]
