# Generated by Django 4.2.6 on 2024-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_customer_user'),
        ('display', '0006_rename_service_service_booking_service_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service_booking',
            new_name='serviceBooking',
        ),
    ]
