# Generated by Django 4.2.6 on 2024-02-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_rename_service_booking_servicebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='service_id',
            new_name='service',
        ),
    ]
