# Generated by Django 5.0.1 on 2024-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
