# Generated by Django 4.2.6 on 2024-02-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_alter_profile_table'),
        ('display', '0008_rename_service_id_servicebooking_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.services')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
