# Generated by Django 4.2.6 on 2024-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
