# Generated by Django 4.2.6 on 2024-02-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
