# Generated by Django 4.2.6 on 2024-03-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0006_delete_email'),
        ('display', '0012_alter_payment_id_alter_servicebooking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer')),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.packages')),
            ],
            options={
                'db_table': 'package_booking',
            },
        ),
    ]
